### ISSUE TITLE
React Mysql + Amazon RDS Aurora

### ISSUE THREAD

**Issue by proneoas** [friends-of-reactphp/mysql#14] opened 2016-10-28 11:29 UTC
The connection silently fails and it does not work 
while if i use Amazon RDS Mysql, it works just fine, how can i debug this issue ?

**Comment by clue** [comment] 2018-03-12 16:18
It sounds like this may be a duplicate of #9, I'll look into this soon-ish :+1:

**Closed by clue** 2018-03-12 16:18 UTC
