### ISSUE TITLE
Undefined property: React\MySQL\Commands\QueryCommand::$resultRows

### ISSUE THREAD

**Issue by DangerLifter** [friends-of-reactphp/mysql#16] opened 2017-02-08 05:13 UTC
I have application running 24 hrs which uses async code. And rarely but stable I got error: "Undefined property: React\MySQL\Commands\QueryCommand::$resultRows". Below log, that is all I have so far. I tried to reproduce error, but no luck. "Bad" query works fine in tests cases.

```
exception 'ErrorException' with message 'Undefined property: React\MySQL\Commands\QueryCommand::$resultRows' in /home/projects/Scraper/library/DomainScrapper/LinkDatabase/MysqlLinkDatabase.php:432
Stack trace:
#0 /home/projects/Scraper/library/DomainScrapper/LinkDatabase/MysqlLinkDatabase.php(432): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/home/projects/...', 432, Array)
#1 /home/projects/Scraper/vendor/react/mysql/src/Connection.php(103): DomainScrapper\LinkDatabase\MysqlLinkDatabase->DomainScrapper\LinkDatabase\{closure}(Object(React\MySQL\Commands\QueryCommand), Object(React\MySQL\Connection))
#2 [internal function]: React\MySQL\Connection->React\MySQL\{closure}(Object(React\MySQL\Commands\QueryCommand), Object(React\MySQL\Connection))
#3 /home/projects/Scraper/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Object(Closure), Array)
#4 /home/projects/Scraper/vendor/react/mysql/src/Protocal/Parser.php(318): Evenement\EventEmitter->emit('success', Array)
#5 /home/projects/Scraper/vendor/react/mysql/src/Protocal/Parser.php(219): React\MySQL\Protocal\Parser->onSuccess()
#6 [internal function]: React\MySQL\Protocal\Parser->parse('365.com\x12\x00\x00\xB8\x11efi...', Object(React\Socket\Connection))
#7 /home/projects/Scraper/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#8 /home/projects/Scraper/vendor/react/socket/src/Connection.php(15): Evenement\EventEmitter->emit('data', Array)
#9 [internal function]: React\Socket\Connection->handleData(Resource id #398, Object(React\EventLoop\LibEventLoop))
#10 /home/projects/Scraper/vendor/react/event-loop/LibEventLoop.php(335): call_user_func(Array, Resource id #398, Object(React\EventLoop\LibEventLoop))
#11 [internal function]: React\EventLoop\LibEventLoop->React\EventLoop\{closure}(Resource id #398, 2, NULL)
#12 /home/projects/Scraper/vendor/react/event-loop/LibEventLoop.php(211): event_base_loop(Resource id #69, 1)
#13 /home/projects/Scraper/library/DomainScrapper/Worker/Main.php(163): React\EventLoop\LibEventLoop->run()
#14 /home/projects/Scraper/library/DomainScrapper/Worker/Manager.php(839): DomainScrapper\Worker\Main->run(Array)
#15 /home/projects/Scraper/app/commands/WorkerRun.php(44): DomainScrapper\Worker\Manager::run('5565:3430:Worke...', '0/10/0/0/0')
#16 /home/projects/Scraper/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): WorkerRun->fire()
#17 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/projects/Scraper/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(WorkerRun), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/projects/Scraper/crawler(23): Symfony\Component\Console\Application->run()
#23 {main} [] []
```

**Comment by DangerLifter** [comment] 2017-02-08 05:30
And It happens on "SELECT" query!

**Comment by DangerLifter** [comment] 2017-02-08 05:48
When I started process first error in callback and continue use mysql client It crashes right after with error:

[2017-02-07 14:01:03] local.ALERT: exception 'RuntimeException' with message 'Can't shift from an empty datastructure' in /home/projects/Scraper/vendor/react/mysql/src/Protocal/Parser.php:277
Stack trace:
#0 /home/projects/Scraper/vendor/react/mysql/src/Protocal/Parser.php(277): SplQueue->dequeue()
#1 [internal function]: React\MySQL\Protocal\Parser->parse('veconsulting.me...', Object(React\Socket\Connection))
#2 /home/projects/Scraper/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(64): call_user_func_array(Array, Array)
#3 /home/projects/Scraper/vendor/react/socket/src/Connection.php(15): Evenement\EventEmitter->emit('data', Array)
#4 [internal function]: React\Socket\Connection->handleData(Resource id #398, Object(React\EventLoop\LibEventLoop))
#5 /home/projects/Scraper/vendor/react/event-loop/LibEventLoop.php(335): call_user_func(Array, Resource id #398, Object(React\EventLoop\LibEventLoop))
#6 [internal function]: React\EventLoop\LibEventLoop->React\EventLoop\{closure}(Resource id #398, 2, NULL)
#7 /home/projects/Scraper/vendor/react/event-loop/LibEventLoop.php(211): event_base_loop(Resource id #69, 1)
#8 /home/projects/Scraper/library/DomainScrapper/Worker/Main.php(163): React\EventLoop\LibEventLoop->run()
#9 /home/projects/Scraper/library/DomainScrapper/Worker/Manager.php(839): DomainScrapper\Worker\Main->run(Array)
#10 /home/projects/Scraper/app/commands/WorkerRun.php(44): DomainScrapper\Worker\Manager::run('23206:6461:Work...', '0/10/0/0/0')
#11 /home/projects/Scraper/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): WorkerRun->fire()
#12 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/projects/Scraper/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(WorkerRun), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/projects/Scraper/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/projects/Scraper/crawler(23): Symfony\Component\Console\Application->run()

**Comment by DangerLifter** [comment] 2017-12-10 07:42
I think it is result of: https://github.com/bixuehujin/reactphp-mysql/issues/28

**Comment by clue** [comment] 2018-03-12 16:22
Possible duplicate of #28.

**Closed by clue** 2018-03-12 16:22 UTC
Labels: bug
