### ISSUE TITLE
why I am getting this error

### ISSUE THREAD

**Issue by lajeeshk** [friends-of-reactphp/mysql#191] opened 2023-12-16 17:04 UTC
Connection to mysql://root:***@localhost/testdb failed during authentication: Client does not support authentication protocol requested by server; consider upgrading MySQL client (EACCES)

**Comment by clue** [comment] 2023-12-17 11:04
Closing as duplicate of #112. Please take the time to use the search before reporting issues. Thank you.

**Closed as not planned by clue** 2023-12-17 11:04 UTC
Labels: question
